# /etc/supervisor/conf.d/frappe-mcp.conf
[program:frappe-mcp]
command=bench --site [define your site name] execute ampower_jive.mcp.config.setup.start_mcp_server
directory=/opt/bench/frappe-bench
user=erp-user
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/opt/bench/frappe-bench/logs/mcp.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=FRAPPE_SITE="[define your site name]",MCP_HOST="0.0.0.0",MCP_PORT=[define your MCP port number]
